#!/bin/bash
echo "routerProgram BEGIN"
gcc -pthread -o routerProgram routerProgram.c source/initRoutingP.c source/userHost.c source/utilityFun.c source/protocolStructure.c source/routerHost.c source/debugging.c
echo "routerProgram END"
echo "*********************************************************************"
echo "userProgram BEGIN"
gcc -pthread -o userProgram userProgram.c source/initRoutingP.c source/userHost.c source/utilityFun.c source/protocolStructure.c source/routerHost.c source/debugging.c
echo "userProgram END"
echo "*********************************************************************"

